version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ink_store_user
      POSTGRES_PASSWORD: thelaw0000
      POSTGRES_DB: ink_store_db
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infrastructure_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql